### ISSUE TITLE
Can't install/add runjs 3.3.0

### ISSUE THREAD

**Issue by bmcallis** [pawelgalazka/runjs#56]
Running `npm install runjs@3.3.0` fails with the error `npm ERR! cb() never called!`

Running `yarn add runjs@3.3.0` fails with the error `error An unexpected error occurred: "https://registry.yarnpkg.com/runjs/-/runjs-3.3.0.tgz: invalid tar file".`

I'm running on macOS Sierra 10.12.4 
node 6.10.2
npm 3.10.10
yarn v.0.21.3

```
$ npm run install runjs@3.3.0 --verbose
npm install runjs@3.3.0 --verbose
npm info it worked if it ends with ok
npm verb cli [ '/Users/bjm/.nvm/versions/node/v6.10.2/bin/node',
npm verb cli   '/Users/bjm/.nvm/versions/node/v6.10.2/bin/npm',
npm verb cli   'install',
npm verb cli   'runjs@3.3.0',
npm verb cli   '--verbose' ]
npm info using npm@3.10.10
npm info using node@v6.10.2
npm verb request uri https://registry.npmjs.org/runjs
npm verb request no auth needed
npm info attempt registry request try #1 at 8:05:48 AM
npm verb request id c90e8520473291ab
npm verb etag W/"590c7a63-b8d4"
npm verb lastModified Fri, 05 May 2017 13:13:07 GMT
npm http request GET https://registry.npmjs.org/runjs
npm http 304 https://registry.npmjs.org/runjs
npm verb headers { date: 'Sat, 06 May 2017 13:05:49 GMT',
npm verb headers   via: '1.1 varnish',
npm verb headers   'cache-control': 'max-age=300',
npm verb headers   etag: 'W/"590c7a63-b8d4"',
npm verb headers   age: '230',
npm verb headers   connection: 'keep-alive',
npm verb headers   'x-served-by': 'cache-dfw1826-DFW',
npm verb headers   'x-cache': 'HIT',
npm verb headers   'x-cache-hits': '1',
npm verb headers   'x-timer': 'S1494075949.493643,VS0,VE0',
npm verb headers   vary: 'Accept-Encoding' }
npm verb etag https://registry.npmjs.org/runjs from cache
npm verb get saving runjs to /Users/bjm/.npm/registry.npmjs.org/runjs/.cache.json
npm verb correctMkdir /Users/bjm/.npm correctMkdir not in flight; initializing
npm verb cache add spec runjs@3.3.0
npm verb addNamed "3.3.0" is a plain semver version for runjs
npm verb addNameVersion registry:https://registry.npmjs.org/runjs not in flight; fetching
npm verb get https://registry.npmjs.org/runjs not expired, no request
npm verb afterAdd /Users/bjm/.npm/runjs/3.3.0/package/package.json not in flight; writing
npm verb correctMkdir /Users/bjm/.npm correctMkdir not in flight; initializing
npm verb afterAdd /Users/bjm/.npm/runjs/3.3.0/package/package.json written
npm ERR! cb() never called!
```

```
$ cat yarn-error.log
Arguments:
  /Users/bjm/.nvm/versions/node/v6.10.2/bin/node /usr/local/bin/yarn add runjs@3.3.0

PATH:
  /Users/bjm/.nvm/versions/node/v6.10.2/bin:./node_modules/.bin:/usr/local/bin:/Users/bjm/.yarn/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/bjm/bin:/usr/local/sbin

Yarn version:
  0.21.3

Node version:
  6.10.2

Platform:
  darwin x64

npm manifest:
  {
    "name": "demo",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {
      "test": "echo \"Error: no test specified\" && exit 1"
    },
    "keywords": [],
    "author": "",
    "license": "ISC"
  }

yarn manifest:
  No manifest

Lockfile:
  No lockfile

Trace:
  Error: https://registry.yarnpkg.com/runjs/-/runjs-3.3.0.tgz: invalid tar file
      at Extract.Parse._startEntry (/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:149:13)
      at Extract.Parse._process (/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:131:12)
      at BlockStream.<anonymous> (/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:47:8)
      at emitOne (events.js:96:13)
      at BlockStream.emit (events.js:188:7)
      at BlockStream._emitChunk (/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:145:10)
      at BlockStream.flush (/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:70:8)
      at BlockStream.end (/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/node_modules/block-stream/block-stream.js:66:8)
      at Extract.Parse.end (/usr/local/Cellar/yarn/0.21.3/libexec/lib/node_modules/yarn/node_modules/tar/lib/parse.js:86:23)
      at UnpackStream.onend (_stream_readable.js:511:10)
```

**Comment by pawelgalazka** [comment]
@bmcallis should be fixed now. Tried to publish by `yarn publish` this time, but something is not working by it. Did good old `npm publish`, now should be fine.

**Comment by bmcallis** [comment]
Yep, looks good.
