### ISSUE TITLE
wish: better diagnostic instead of "TypeError: Cannot read property 'help' of undefined"

### ISSUE THREAD

**Issue by markstos** [pawelgalazka/runjs#88]
As I setup my runfile, I've got this error several times. I know the cause is in my own code, but the error message only points to the internals of runjs. It would be helpful if this condition was checked for with a `try/catch` and clearer diagnostic was emitted that pointed tot he line with the problem:

```
TypeError: Cannot read property 'help' of undefined
    at Object.keys.forEach.key (/path/node_modules/runjs/lib/script.js:95:24)
    at Array.forEach (<anonymous>)
    at describe (/path/node_modules/runjs/lib/script.js:92:20)
    at Object.main (/path/node_modules/runjs/lib/script.js:189:7)
    at Object.<anonymous> (/path/node_modules/runjs/bin/run.js:26:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by markstos** [comment]
In `src/index.js`, it looks like the intent is there to validate the input as receiving a value that is a function:

```
export function help(func: () => void, annotation?: string | Object) {
```
But when this code is compiled into `./lib/index.js`, the validation is currently stripped, allowing undefined values to be passed through:

```
function help(func, annotation) {
  func.help = annotation;
}
```
